global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093" 
rule_files:
  - alertrules.yml

scrape_configs:
  - job_name: 'prometheus_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: 'nginx_prometheus_exporter_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']
      
