Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.define "node" do |subconfig|
   subconfig.vm.box_download_insecure = true
   subconfig.vm.box = "ubuntu/bionic64"
   subconfig.vm.network "public_network", ip: "192.168.1.40", bridge: "wlp2s0"
   subconfig.vm.hostname = "ms-machine"
   subconfig.vm.provider "virtualbox" do |v|
      v.name= "ms-machine"
      v.memory = 2048
      v.cpus = 1
      v.gui = true
    end
    subconfig.vm.provision "shell" do |s|
      ssh_pub_key_path = "#{Dir.home}/.ssh/id_rsa.pub"
      print "Checking if SSH key exist in host... \n"
      # Check if the SSH public key exists, and create it if it doesn't
      unless File.exist?(ssh_pub_key_path)
        print " ==> Generating SSH key... \n"
        system("ssh-keygen -t rsa -f #{Dir.home}/.ssh/id_rsa -N ''")
      end
      ssh_pub_key = File.readlines(ssh_pub_key_path).first.strip
      s.inline = <<-SHELL
       sudo apt update  
       sudo apt install ansible sshpass -y
       echo -e "Add host public SSH key to guest authorized keys... \n"
       echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  end
end
