---
- hosts: DockerCompose
  become: true
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - gnupg
      - software-properties-common
      - lsb-release

  - name: Add an apt signing key for Docker
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /usr/share/keyrings/docker-archive-keyring.gpg
  
  - name: Add a key from a file
    apt_key:
       file: /usr/share/keyrings/docker-archive-keyring.gpg 
       state: present 

  - name: Get system architecture
    shell: dpkg --print-architecture
    register: system_arch
    changed_when: false
    
  - name: Get ubuntu codename
    shell: lsb_release -cs
    register: ubuntu_codename
    changed_when: false

  - name: Add apt repository
    apt_repository:
      repo: deb [arch={{system_arch.stdout}} signed_by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ubuntu_codename.stdout}} stable
      state: present
      filename: docker

  - name: Install docker and its dependecies
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
    notify:
      - docker status

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  - name: Copy monitoring-system-compose directory from ansible controller
    copy:
      src: /home/vagrant/Monitoring_System/monitoring-system-compose/
      dest: monitoring-system-compose/
      
  handlers:
    - name: docker status
      service: name=docker state=started
