services:

  nginx:
    image: nginx:1.25.3-alpine3.18
    conatiner_name: nginx
    restart: always
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf
    networks:
      - monitor
    ports:
      - 80:80
      - 8080:8080
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alertrules.yml:/etc/prometheus/alertrules.yml
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
    restart: always
    networks:
      - monitor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    restart: always
    networks:
      - monitor

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100
    restart: always
    networks:
      - monitor

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alert-manager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    restart: always
    networks:
      - monitor
      
  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.0
    container_name: prometheus-nginx-exporter
    restart: always
    command:
      - -nginx.scrape-uri=https://nginx/stub_status
    ports: 
      - 9113:9113
    networks:
      - monitor
    depends_on:
      - prometheus

networks:
  monitor:  
    driver: bridge

