services:

  nginx:
    image: nginx:1.25.3-alpine3.18
    restart: always # Ensures the container automatically restarts if it stops.
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/status.conf  # Mounts a custom NGINX config file to expose a status endpoint.
    networks:
      - monitor # Connects the NGINX service to the "monitor" network for communication with other services.
    ports:
      - 80:80
      - 8080:8080
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # Mounts the Prometheus configuration file.
      - ./prometheus/alertrules.yml:/etc/prometheus/alertrules.yml # Mounts alerting rules for Prometheus.
    command:
      - '--storage.tsdb.path=/prometheus' # Sets the path for storing time-series data.
      - '--storage.tsdb.retention.time=7d' # Configures data retention for 7 days.
      - '--config.file=/etc/prometheus/prometheus.yml' # Specifies the config file location.
      - '--web.console.templates=/etc/prometheus/consoles' # Sets the path for console templates.
      - '--web.console.libraries=/etc/prometheus/console_libraries' # Sets the path for console libraries.
    restart: always
    networks:
      - monitor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus # Ensures Prometheus starts before Grafana.
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning # Mounts provisioning files for Grafana setup.
      - ./grafana/dashboards:/var/lib/grafana/dashboards # Mounts custom Grafana dashboards.
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini # Mounts Grafana configuration.
    restart: always
    networks:
      - monitor

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100
    restart: always
    networks:
      - monitor

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alert-manager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml # Mounts the Alertmanager configuration file.
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml  # Specifies the Alertmanager configuration file.
    restart: always
    networks:
      - monitor
      
  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.0
    container_name: prometheus-nginx-exporter
    restart: always
    command:
      - -nginx.scrape-uri=http://nginx:8080/stub_status # Configures the exporter to scrape NGINX metrics from the status endpoint.
    ports: 
      - 9113:9113
    networks:
      - monitor
    depends_on:
      - prometheus # Ensures Prometheus starts before the exporter.

networks:
  monitor:  
    driver: bridge # Creates a bridge network named "monitor" for inter-service communication.

